version: '3'

tasks:
    hello:
        cmds:
            - echo 'Hello World from Task!'
        silent: true
    dbuild:
        cmds:
            - docker build -t go-server .
    drun:
        cmds:
            - docker run -it --rm --name go-server -p 8080:80 go-server
    
